### ISSUE TITLE
text background color should be a gradient

### ISSUE THREAD

**Issue by colinsullivan** [karmapa/kagyumonlam.org#3]
instead of the transparent background that it is now

see mockup:

![image](https://cloud.githubusercontent.com/assets/94535/21795632/2fbc3418-d6b8-11e6-8328-1972375e805a.png)

**Comment by carloslokko** [comment]
Thisa background is great. Let's use it and forget the flags

**Comment by tallt0m** [comment]
+1 - lgtm
