### ISSUE TITLE
When the browser window is greater than 765px, Navigation is included in the main page.

### ISSUE THREAD

**Issue by colinsullivan** [karmapa/kagyumonlam.org#7]
@tallt0m raised this concern

**Comment by colinsullivan** [comment]
This was partially on purpose, we haven't discussed having a hidden navigation for large screens.  Seems to me if there is enough real estate it shouldn't be hidden.

There was a also a layout bug that was just fixed, so closing this issue for now and we can start a new issue for further discussion.

**Comment by tallt0m** [comment]
LGTM
